spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/mykart?&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false

eureka:
  client:
    serviceUrl:
      defaultZone: http://mykart-eureka-container:8083/eureka