server:
  port: 8081
  error:
    include-message: ALWAYS

spring:
  profiles:
    active: container
  application:
    name: product-service
  main:
    banner-mode: "off"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://host.docker.internal:3306/mykart?&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd

logging:
  level:
    root: ERROR
    com.mykart: DEBUG
    org.springframework.web: ERROR
    org.hibernate: ERROR
    org.springframework.cache: TRACE

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true